version: '3.1'

services:

  back_docker:
    image: pepitoespana/back_docker
    restart: always
    ports:
      - 8000:8000

  front_docker:
    image: pepitoespana/front_docker
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back_docker
