version: '3.1'

services:

  back_docker:
    image: pepitoespana/back_docker
    restart: always

  front_docker:
    image: pepitoespana/front_docker
    restart: always
    depends_on:
      - back_docker
