version: '3.4'

services:
  front:
    image: pepitoespana/front:latest
  back:
    image: pepitoespana/back:latest
  lb:
    depends_on:
      - front
      - back
    ports:
      - "8000:80"
  db:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=decide
      - MONGO_INITDB_ROOT_USERNAME=decide
      - MONGO_INITDB_ROOT_PASSWORD=decide
      - MONGO_INITDB_USER=decide
      - MONGO_INITDB_PD=decide
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongo_data:/data/decide
volumes:
  mongo_data: {}
