name: Python application

on:
  push:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0, 14.15.0]
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: decide
        ports:
          - 27017:27017
        options: --health-cmd mongo --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install decide dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codacy-coverage
      - name: Run migrations
        run: cd decide;python manage.py makemigrations;python manage.py migrate
      - name: Run decide tests
        run: cd decide;coverage run --branch --source=. ./manage.py test --settings=decide.test_settings --keepdb; coverage xml;
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install decide_panel dependencies
        run: cd decide_panel && npm install
      - name: Deploy decide
        run: |
          cd decide && 
          python manage.py runserver --settings=decide.test_settings &
      - name: Deploy decide_panel
        run: |
          cd decide_panel && 
          npm run start:local &
      - name: Test React app
        run: cd decide_panel && npm run test:e2e
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: decide/coverage.xml
      - name: Codacy Coverage Reporter React
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: decide_panel/coverage/clover.xml

  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest


name: Python Frontend application

on:
  push:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0, 14.15.0]
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_DATABASE: decide
        ports:
          - 27017:27017
        options: --health-cmd mongo --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install decide dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install codacy-coverage
      - name: Run migrations
        run: cd decide;python manage.py makemigrations;python manage.py migrate
      - name: Run decide tests
        run: cd decide;coverage run --branch --source=. ./manage.py test --settings=decide.test_settings --keepdb; coverage xml;
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install decide_panel dependencies
        run: cd decide_panel && npm install
      - name: Deploy decide
        run: |
          cd decide && 
          python manage.py runserver --settings=decide.test_settings &
      - name: Deploy decide_panel
        run: |
          cd decide_panel && 
          npm run start:local &
      - name: Test React app
        run: cd decide_panel && npm run test:e2e
      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: decide/coverage.xml
      - name: Codacy Coverage Reporter React
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: decide_panel/coverage/clover.xml

  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t front .
      - name: Tags
        run: |
          docker tag front ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker tag front ${{ secrets.DOCKER_USER }}/front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/front:latest

